### ISSUE TITLE
Comparison against Panama?

### ISSUE THREAD

**Issue by TheMode** [apangin/nalim#1]
I know that their JNI replacement isn't out yet, but including it in the bench seems reasonable. And may push them into providing a critical's replacement as well:)

**Comment by apangin** [comment]
Would you like to prepare such a benchmark? I'll include it in comparison then.

**Comment by apangin** [comment]
Updated `add` benchmark results with the numbers for Panama FFI (spoiler: it's on par with JNI).

Since Panama FFI does not currently provide a zero-copy access to on-heap arrays, there is no Panama equivalent for the `max` benchmark.
