### ISSUE TITLE
Arbitrary objects as parameters are possible, it seems

### ISSUE THREAD

**Issue by httpdigest** [apangin/nalim#2]
First of all: **Fantastic idea and library!**

You write under "Limitations":
> 3. Only primitive types and primitive arrays can be passed as arguments.

I wonder where this limitation is coming from, since when passing an arbitrary object, you will simply be given the actual object virtual address in the respective register of the calling convention.
When combined with sun.misc.Unsafe to find/validate the field offsets, you can actually do crazy stuff like using SSE/AVX to accelerate operations on float/double fields in your class, when they are consecutive.

So, when being careful here and first validating the field offsets that you expect and using native code via the `@Code()` annotation, we can access and manipulate the object fields, can't we?

I've used your library to accelerate matrix multiplications from 10.5 ns. to just 4.0 ns. per operation for a class which uses 16 consecutive float fields: https://github.com/JOML-CI/joml-nalim

**Comment by httpdigest** [comment]
Closing, as apparently Nalim has built-in support for Java arrays due to the fact that it determines the array base offset itself and hands the native function just the array data starting at its base: https://github.com/apangin/nalim/blob/045ba37a2773f31d532c8cd82ec5f4d783d42098/src/one/nalim/AMD64LinuxCallingConvention.java#L88
Arguably, in theory this could also be done for other objects (at least to subtract the object header size) but accessing any fields would of course require the native function to somehow obtain instance field offsets (as extra arguments).

**Comment by apangin** [comment]
Added `@FieldOffset` annotation to pass pointers to object fields.
