### ISSUE TITLE
is it possible to add int[] code as byte[] without converting to the main version?

### ISSUE THREAD

**Issue by orabelt** [apangin/nalim#3]
f.e.  
@Code({(byte)0x48, (byte)0x31, (byte)0xC0, (byte)0xC3})
public static native long test();

**Comment by apangin** [comment]
I'm thinking of changing the `@Code` to hex string, e.g.
```
    @Code("0f31 48c1e220 4809d0 c3")
    public static native long rdtsc();
```

**Comment by orabelt** [comment]
it's wonderful also ^)

**Comment by apangin** [comment]
Changed to hex string
